import Head from 'next/head';
import Header from '../components/header';
import MainContentLayout from '../components/layout/mainContentLayout';
import Top from '../components/top';

export default function Home() {
  const content1 = <div>TEST1</div>;
  const content2 = <div>TEST2</div>;
  const content3 = <div>TEST3</div>;

  const testContent = [content1, content2, content3];
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header />
      <Top />
      <MainContentLayout contents={testContent}></MainContentLayout>
    </div>
  );
}
